### ISSUE TITLE
Request to add new project googleinterns/dagger-query

### ISSUE THREAD

**Issue by margaritiko** [bazelbuild/continuous-integration#1014]
- I want to test the following project on Bazel CI: https://github.com/googleinterns/dagger-query
- I confirm that the project has a `.bazelci/presubmit.yml` file.

😊✨

**Comment by fweikert** [comment]
I've created the pipeline. The build is currently failing since you need top-level WORKSPACE and BUILD files: https://buildkite.com/bazel/dagger-query/builds/1#81b92aec-2cfd-46b3-ab11-1ab346494eae

Documentation for Bazel 2.1.0 [*]: https://docs.bazel.build/versions/2.1.0/build-ref.html

I'll send you an email with instructions on how to set up GitHub integration for presubmit testing.

[*] Is there a particular reason why you're using an old version?

**Comment by fweikert** [comment]
I've also sent you invitations to join our Buildkite org. The pipeline is public, but as a member of the org you can edit its settings, too.

**Comment by margaritiko** [comment]
Thanks for the help with setup! 🚀
