### ISSUE TITLE
Android testing project needs system images v19,v21,v22,v23

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1026]
Resolving https://github.com/bazelbuild/continuous-integration/issues/1006 the system images were removed.

Project "Android testing" needs them. Cannot upgrade it to v29, as the emulator is not supported by Bazel.

```
sdkmanager --install 'system-images;android-19;default;x86' 'system-images;android-21;default;x86' 'system-images;android-22;default;x86' 'system-images;android-23;default;x86'
```

**Comment by philwo** [comment]
Oh, sorry! Bazel CI does not support running the Android emulator (anymore) as it requires support for Nested Virtualization. I thought "Android Testing" runs the tests that require the emulator on RBE and that the system images then would be directly embedded in the RBE container image?

But I can add them again if it helps, no problem.

**Comment by comius** [comment]
Android Testing is running without RBE
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1616#6a69ea82-2170-40e7-8abb-29b42f123901

However there is also rules_jvm_external running on RBE and failing:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1616#3c32e2fb-ea4e-48eb-859c-fe1e8174c833

**Comment by philwo** [comment]
I'm building new images with the emulator and system images now and will retry the failed jobs then, will close this bug when everything is green again.

**Comment by philwo** [comment]
@jin Apparently "Android Testing" still needs the Android emulator, the system-images and Nested KVM support (because it tries to run the emulator) during the `bazel build` phase, which doesn't run on RBE: https://buildkite.com/bazel-testing/android-testing/builds/23#7df9fe0e-1e61-4a2b-b557-55327eeba490

Is this WAI? It's the last remaining blocker for disabling Nested KVM, which prevents us from migrating to cheaper instance types. If there's no way around it, that's fine, but if we could somehow remove that requirement, it would be really nice.

**Comment by philwo** [comment]
Android Testing is green again, at last.
