### ISSUE TITLE
Add verification job for gerrit@RBE

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#1072]
It would be great to extend gerrit verification job to run also on RBE (like Bazel itself).

Something like this works for me:

```sh
  $ bazel test --config=remote --remote_instance_name=<project-name> javatests/...
```

This would help detect Bazel RBE regressions, e.g.: https://github.com/bazelbuild/bazel/issues/12705.

**Comment by davido** [comment]
@meteorcloudy

What would need to be done to enable Gerrit verification on RBE?
Or downstream project shouldn't be tested on RBE?

**Comment by meteorcloudy** [comment]
Change the platform name from `ubuntu2004` to `rbe_ubuntu2004` would probably do. 

But it's a bit hard to test it since the config file is CI repo: https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/gerrit.yml#L3C3-L3C13

I think it'll be helpful if the Gerrit repo can host this config file.

**Comment by meteorcloudy** [comment]
Done in https://github.com/bazelbuild/continuous-integration/pull/1829
