### ISSUE TITLE
Request to add new project: google/cargo-raze

### ISSUE THREAD

**Issue by acmcarther** [bazelbuild/continuous-integration#1084]
- I want to test the following project on Bazel CI: https://github.com/google/cargo-raze
- I confirm that the project has a `.bazelci/presubmit.yml` file.:  https://github.com/google/cargo-raze/blob/master/.bazelci/presubmit.yml

I have already created a (probably broken) pipeline: https://buildkite.com/bazel/cargo-raze. Sorry if that proves to be inconvenient!

This project is a rules_rust "adjacent" project which supports Bazel Rust users in accessing third-party packages in the Rust ecosystem. It previously used Travis CI, but that has since died. The current very minimal presubmit.yml is my "low confidence" first attempt. I expect to extend it once we've got the basic stuff working.

**Comment by UebelAndre** [comment]
@meteorcloudy do you have a quick moment to take a look at this 🙏 😅

**Comment by meteorcloudy** [comment]
Hi @acmcarther @UebelAndre , I fixed some setup in the pipeline setting and created daily build schedule for https://buildkite.com/bazel/cargo-raze.

Can you please take a look at the failing tests (especially on Windows)? Once this pipeline is green, I can add cargo-raze to our [downstream pipeline](https://buildkite.com/bazel/bazel-at-head-plus-downstream) so that it's tested with Bazel@HEAD and you'll get notified as soon as there is any breaking changes in Bazel.

**Comment by acmcarther** [comment]
Thanks for setting that up!

I've spent some time looking at this. It's pretty broken (from cargo-raze's own jank non-hermetic stuff). I'll continue looking tomorrow.

**Comment by acmcarther** [comment]
I've disabled the windows builds for now. Everything else is green. I'm not sure if this is sufficient for inclusion in the downstream pipeline. I think either way is OK.

@meteorcloudy Is it possible to toggle the CI pipeline to public? I don't seem to have that knob in my Pipeline Settings configuration.

**Comment by meteorcloudy** [comment]
@acmcarther Thanks! Cargo-Raze is now public, I'll enable it in Bazel downstream.
