### ISSUE TITLE
CloudRoboticsCore broken

### ISSUE THREAD

**Issue by comius** [bazelbuild/continuous-integration#1106]
Autosherif determined it's infra issue.

```
Main build: FAILED
Downstream build: FAILED
Project failed at last green commit. 
```

But it appears some of the modules the project depends on require Python 3:
```
(rsa requires Python '>=3.5, <4' but the running Python is 2.7.17
```

**Comment by fweikert** [comment]
@philwo : related to your recent changes?

**Comment by philwo** [comment]
We didn't have any changes on the Linux infra recently that I'm aware of. I would rather assume that this is caused by an unpinned Python dependency somewhere and that `rsa` recently dropped support for Python 2.x.

Looks like Cloud Robotics Core "fixed" this issue by removing all their Python stuff :D

- https://buildkite.com/bazel/cloud-robotics-core/builds/3938
- https://github.com/googlecloudrobotics/core/commit/06bc23c754bfafa920ef33c537bc2449fb757cc0
