### ISSUE TITLE
Downstream projects report: add information from the same pipeline as well as latest release pipeline

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/continuous-integration#115]
Check this report: http://ci.bazel.io/job/Global/job/pipeline/175/Downstream_projects/
It compares Global/ pipeline with latest release pipeline (e.g. `bazel-tests  #124 (was  #928)`)

Not sure it it is intended that way or not, at any rate the report should show the last failing job from exact same location as well (e.g. previous run of Global/bazel-tests compared to this run).

**Comment by dslomov** [comment]
This is what would be nice to see: `bazel-tests (red) #124 (was Global (green) #124, latest (grreen) #928)`

**Comment by damienmg** [comment]
I am sorry but I do not understand. Though i can understand that we might want to replace the "was" by "was with latest bazel release" to be more explicit, I cannot see what information latest global is good for, especially extracting that information might be tricky (because of presubmits, and release build and so on). You generally want to know If the project is already broken with latest release to find a regression, not if it was broken with previous head.

I was thinking at some point to show a better view for the dashboard with one that shows a matrix with list of global post-submit and their relative build to be able to feel if we start doing better or worse but that's would be a whole new feature and I actually did not engage in doing so because of the benefit is unclear.

**Comment by dslomov** [comment]
Seeing the previous build from the same pipeline is super-useful for the sheriff to assess the health of things. It is nice to have one view that shows you everything - then you can zero in on what happened in the latest set of commits on particular architecture. 

(There is a general theme in Jenkins UI: one has to fish around a lot for information one needs.)

**Comment by damienmg** [comment]
I agree that seeing the history is a nice to have, a bit like what we get with the [test result analyzer](http://ci.bazel.io/job/bazel-tests/test_results_analyzer/) and that's what I was thinking about the matrix of global post-submit.

Anyway that's a different story than just updating the text on the line, for which I still fail to see how this can be a useful information because the build of TF on last run might be failing because of a TF failure while at head it fails because we changed bazel (of course we would see a green TF for latest bazel but the information about the last build from the global pipeline is useless and might be confusing).

PS: I filed #120 for cleaning up a bit the jobs, that should also make extracting the history easier.

**Comment by dslomov** [comment]
I do not know why you say that the state of the previous run at HEAD is useless :) I find it very useful to see at a glance what is the state of things. We can make it non-confusing with clear labelling

**Comment by damienmg** [comment]
So let me give some examples:

Example 1:

* Build 1 TF is broken with latest, TF is broken with HEAD
* Build 2 TF is clear with latest, TF is broken with HEAD
* ==> You report: `broken (was Global broken, latest green)`

Example 2:

* Build 1 TF is clear with latest, TF is broken with HEAD
* Build 2 TF is clear with latest, TF is broken with HEAD
* ==> You report: `broken (was Global broken, latest green)`


Example 3:

* Build 1 TF is clear with latest, TF is clear with HEAD
* Build 2 TF is clear with latest, TF is broken with HEAD
* ==> You report: `broken (was Global clear, latest green)`


In all those case, I fail to see how the status of past Global is informative without more information (e.g. without the status of latest during build 1 that would give a sense of history, e.g. are we getting worse or better).


The way I was seeing a possible evolution of the view was:

| Build | TensorFlow .       | bazel-tests | ... |
|------|-----------------|-------------|---|
| 2       | Broken / Broken | Red / Green | ... |
| 1       | Broken / Green  | Red / Green | ... |

(latest build top)

**Comment by dslomov** [comment]
First of all, not all projects change as fast as TensorFlow (and for bazel-tests at least there is no divergence between latest and HEAD)
Second, this provides clear information at least in case when TF is clear with latest in both runs: if HEAD changed state something regressed/improved (and "downstream project is clear on latest" will be a should be the most common state)
Third, I as a sheriff need a reminder of the state of things last time I looked (I do not have 100% memory and having a state of previous build at the same page will help me remember things)

**Comment by damienmg** [comment]
1. Right, it also happens to be the most interesting one for that example, but we could have taken other name, the argument still stands.

2. If TF is clear with latest bazel, then if it is not clear with bazel HEAD we need to fix it, whatever was last build with bazel HEAD. Indeed if with bazel latest is clear and latest Global run is clear, then we know that Global red means a regression, but that's in one case out of 4.

3. Right, as a sheriff, I want to see the history as a general indication of how well we do, but if I only see partial information, I'll fail to analyze it. Presenting another build result that does not have an implication on how I should treat the current failure is confusing. I was not seeing that information in the previous UI either.

**Comment by dslomov** [comment]
Please, come on, as I said partial information is better than no information at all, especially for the sheriff. As I said, I just need a *reminder* of how things were last time I looked (surely we need clear labels explaining what is what)

**Comment by philwo** [comment]
Obsolete, as we're migrating away from Jenkins.
