### ISSUE TITLE
Run downstream pipeline on repos using last_green

### ISSUE THREAD

**Issue by keith** [bazelbuild/continuous-integration#1455]
I noticed on [this run](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1264#018355d0-894b-42d1-8611-7390457b890d) that rules_apple and others were excluded because they specify `last_green` in the CI pipeline configuration, but since this was triggered against a relatively new commit, it would be have been fine to run, and potentially identify issues there. Would it be possible to not exclude pipelines specifying `last_green` in the case that we're running this pipeline against a commit?

**Comment by keith** [comment]
@fweikert is this change deployed? On the most recent downstream build there is still a list of things disabled because of pinning to last_green https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2882
<img width="827" alt="image" src="https://user-images.githubusercontent.com/283886/221063092-489b934b-77e9-4f48-8c24-8baf4ab3fa1e.png">

**Comment by fweikert** [comment]
Oh wow, this is funny (and slightly embarrassing):

- The "skip message" is actually WAI since we overwrite the Bazel version in all downstream pipelines. For rules_swift this means that for each platform the "Previous LTS" and "Current LTS" tasks are identical. As a result, I implemented a change to skip one of these identical tasks.
- The funny/embarrassing part is that #1492 incorrectly removed a `continue` statement. As a result, CI warned about skipping tasks, but then executed all of them nonetheless.

#1557 will fix the bug. We should improve the UI to make it more clear that task X was skipped because it's identical to task Y which was executed.

**Comment by fweikert** [comment]
Filed https://github.com/bazelbuild/continuous-integration/issues/1561 for the UX improvement
