### ISSUE TITLE
"Build Bazel" jobs didn't succeed with uploading the artifacts

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1584]
Reference : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2965#01878cf7-f133-4741-a994-b9ccab375cd0

--
```
  |  
  | buildkite-agent artifact upload bazel
  | 2023-04-17 04:08:48 INFO   File not found: bazel
  | 2023-04-17 04:08:48 INFO   No files matched paths: bazel
  | buildkite-agent artifact upload bazel_nojdk
  | 2023-04-17 04:08:48 INFO   File not found: bazel_nojdk
  | 2023-04-17 04:08:48 INFO   No files matched paths: bazel_nojdk
```
Seeing below error in most of all the corresponding downstream projects.

Reference : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2965
2023-04-17 04:06:06 FATAL  Failed to download artifacts: No artifacts found for downloading
```
--
  | Traceback (most recent call last):
  | File "bazelci.py", line 3621, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 3601, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 1259, in execute_commands
  | os.environ["USE_BAZEL_VERSION"] = download_bazel_binary(tmpdir, binary_platform)
  | File "bazelci.py", line 1610, in download_bazel_binary
  | return download_binary(dest_dir, platform, binary_name)
  | File "bazelci.py", line 1600, in download_binary
  | ["buildkite-agent", "artifact", "download", binary_name, dest_dir, "--step", source_step]
  | File "bazelci.py", line 2270, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['buildkite-agent', 'artifact', 'download', 'bazel', '/tmp/tmpcvm98g80', '--step', 'Build Bazel (:centos: 7 (OpenJDK 11, gcc 10.2.1))']' returned non-zero exit status 1.
  | 🚨 Error: The command exited with status 1

```

**Comment by meteorcloudy** [comment]
Tried to rebuild Bazel at the same commit and now it also failed to upload the artifacts:
old: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1630#01877939-8ec0-48d7-a66f-d0cded3b21e8
new: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1635#01878e64-49f3-4f55-b4ba-77d140d7e7ed

therefore this is not caused by a change from Bazel itself.

**Comment by meteorcloudy** [comment]
The culprit is probably https://github.com/bazelbuild/continuous-integration/commit/a95a916098d3015bb4ea20b7e33bc7d27d00bffc where we tried to avoid downloading any artifacts when running a build on CI. But in the "Build Bazel" steps, we actually need the top level build outputs, therefore we should switch to using `--remote_download_toplevel`.
See
https://bazel.build/reference/command-line-reference#flag--remote_download_minimal
https://bazel.build/reference/command-line-reference#flag--remote_download_toplevel

FYI @sgowroji

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1637#01878e93-0ef2-41ee-9d16-6fbbec16c30f

This is now fixed in a latest downstream (+disabled project) run.
