### ISSUE TITLE
Set up CI job for Gerrit on Java 9

### ISSUE THREAD

**Issue by davido** [bazelbuild/continuous-integration#173]
//CC @cushon, @jart.

Bazel@HEAD and upcoming 0.10.0 release should support Java 9 out of the box. Gerrit@HEAD supports Java 9, well, almost, the only missing dependency is this `rules_closure` PR: [1].

Please add a job to Bazel CI to verify Gerrit on Java 9.

[1] https://github.com/bazelbuild/rules_closure/pull/235

**Comment by philwo** [comment]
We'll look into this! Thanks.

**Comment by davido** [comment]
@philwo Thanks. It worth mention, though, that the last needed change is still pending for review: [1]. Also, only upcoming Bazel version, 0.11.0 supports Java 9 out of the box. Once it's merged, the command to build gerrit with Java 9 would be:

```
  $ bazel --host_javabase=/usr/lib64/jvm/java-9-openjdk test \
      --javacopt='--release 9' \
      --java_toolchain=@bazel_tools//tools/jdk:toolchain_jdk9 //...
```

* [1] https://gerrit-review.googlesource.com/#/c/gerrit/+/147234/

**Comment by philwo** [comment]
@davido Thanks for the clear explanation.

I'm OOO next week and we have to do some work on CI and Bazel before we can get this done, so it'll be ~2-3 weeks before I can get to this.

**Comment by davido** [comment]
@philwo Thanks for the update.

**Comment by philwo** [comment]
Update: We now have Ubuntu 18.04 LTS machines with system JDK being OpenJDK 9 and 10.

You can test on these machines by using the "ubuntu1804_java9" and "ubuntu1804_java10" platform in presubmit.yml / postsubmit.yml.

**Comment by davido** [comment]
Sorry, It doesn't tell me anything. I'm not familiar with buildkite.com.

**Comment by philwo** [comment]
No problem and sorry for not explaining better. Basically, we have a config file for Gerrit here: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/gerrit-postsubmit.yml

We can add an entry that tests however you'd like to test Gerrit with Java 9. With @lberki rolling changes back and forth, I'm not sure if the --host_java_toolchain / --java_toolchain flags still apply as you mentioned above, but otherwise this is how it would look like: https://github.com/bazelbuild/continuous-integration/pull/322

**Comment by davido** [comment]
@philwo Thanks. That's clear now. I think that @lberki is rolling back JDK10 embedded JDK and javac support on Bazel@HEAD, but the JDK9 should still work and supported in Gerrit@HEAD.

Thanks a lot for moving Bazel CI forward and supporting newer Java versions. That will assure that future breakages can be detected and track down earlier. Great job!

**Comment by philwo** [comment]
Fixed in the meantime.
