### ISSUE TITLE
Gerrit is failing at Bazel@HEAD in CI and its own CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/continuous-integration#1881]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3666#018dbf86-436c-4324-9858-0e94955dd506/6-7

Platform : MacOS, Windows, Ubuntu

Gerrit: Gerrit (:fedora: 39 (OpenJDK 17, gcc 13.1.1)), Gerrit (:ubuntu: 22.04 (OpenJDK 17, gcc 11.2.0)), Gerrit (:darwin: (OpenJDK 11, Xcode)), Gerrit (RBE :ubuntu: 22.04 (OpenJDK 17, gcc 11.2.0))

MainCI : [https://buildkite.com/bazel/gerrit](https://buildkite.com/bazel/gerrit)

Logs:

```
Script project @//polygerrit-ui/app:compile_pg [tsc -p polygerrit-ui/app/tsconfig_bazel.json] failed: missing input file '@@ui_npm//:node_modules/@polymer/polymer/lib/mixins/element-mixin.js'
(05:03:09) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel-org-repo-root/gerrit/polygerrit-ui/app/BUILD:34:11: Compiling TypeScript project @//polygerrit-ui/app:compile_pg [tsc -p polygerrit-ui/app/tsconfig_bazel.json] failed: missing input file '@@ui_npm//:node_modules/@polymer/polymer/lib/mixins/gesture-event-listeners.d.ts'
(05:03:09) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel-org-repo-root/gerrit/polygerrit-ui/app/BUILD:34:11: Compiling TypeScript project @//polygerrit-ui/app:compile_pg [tsc -p polygerrit-ui/app/tsconfig_bazel.json] failed: missing input file '@@ui_npm//:node_modules/@polymer/polymer/lib/mixins/gesture-event-listeners.js'
(05:03:09) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel-org-repo-root/gerrit/polygerrit-ui/app/BUILD:34:11: Compiling TypeScript project @//polygerrit-ui/app:compile_pg [tsc -p polygerrit-ui/app/tsconfig_bazel.json] failed: missing input file '@@ui_npm//:node_modules/@polymer/polymer/lib/mixins/mutable-data.d.ts'
```

Culprit: bazelbuild/bazel@404d8d9

Gerrit : https://b.corp.google.com/issues/325883861

CC Greenteam @fweikert

**Comment by meteorcloudy** [comment]
@davido Can you please take a look?

**Comment by sgowroji** [comment]
Hi @davido,  Can you please respond on the above [comment](https://github.com/bazelbuild/continuous-integration/issues/1881#issuecomment-1966930478). If this is stale for long time, we will be moving Gerrit to Disabled pipeline. Thanks!

**Comment by meteorcloudy** [comment]
@davido https://buildkite.com/bazel/gerrit/builds/13421#018e6608-660b-481f-afaf-b4e580a7679b Gerrit is also failing to be cloned in https://buildkite.com/bazel/gerrit

**Comment by davido** [comment]
@meteorcloudy @sgowroji I was OOO, sorry for the late response.

> Gerrit is also failing to be cloned in https://buildkite.com/bazel/gerrit

It seems, that it's complaining about `java-prettify` submodule, that I  added in this CL: [1].
It was needed, because it was added to core `gerrit` plugin: `gitiles` in this CL: [2].

However, I am not able to reproduce the cloning issue locally, and also the Gerrit CI is green now:

```bash
davido@wizball:~/projects$ git clone https://gerrit-review.googlesource.com/java-prettify
Cloning into 'java-prettify'...
remote: Total 1563 (delta 1114), reused 1563 (delta 1114)
Receiving objects: 100% (1563/1563), 1.23 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (1114/1114), done.
```

Also, I am able to clone `gerrit` with all submodules, and `java-prettify` is also among them:

```bash
davido@wizball:~/projects$ git clone --recursive https://gerrit-review.googlesource.com/gerrit
[...]
Submodule path 'modules/java-prettify': checked out '32fa081a797a97beaf77a4f2efca26c39168e72f'
Submodule path 'modules/jgit': checked out 'c0b415fb028b4c1f29b6df749323bbb11599495d'
[...]
Submodule path 'polymer-bridges': checked out '855f4781b702de120953a64da5c277ea4908deaa'
```

Also note, that Gerrit and all submodules are hosted on Google infrastructure on googlesource.com.
You might be able to talk to Gerrit Team@Munich directly, e.g. @phiesel, @EdwinKempin and @bro314,
or rise internal issue, on Google issue tracker: [3].

[1] https://github.com/GerritCodeReview/gerrit/commit/04219df2c3ba6e3c25ae6480279391519f02c293
[2] https://github.com/GerritCodeReview/gitiles/commit/acb511d7eead1d66314cabc01da37f9bfbd2be21
[3] https://issues.gerritcodereview.com/issues?q=status:open

**Comment by davido** [comment]
@meteorcloudy @sgowroji

What is the status here?

**Comment by sgowroji** [comment]
CI is Green now. We can close this issue. Thanks @davido for the support.
