### ISSUE TITLE
md5 not installed on macOS

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/continuous-integration#205]
Shell Utils test is failing because md5 is not installed or not in the path.

```
/private/var/tmp/_bazel_ci/39c5ba3d17130df60135f575a949db54/bazel-sandbox/1654426759142794820/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/src/test/shell/shell_utils_test.runfiles/io_bazel/src/test/shell/shell_utils.sh: line 114: md5: command not found
```

**Comment by philwo** [comment]
It's installed on all Mac Pros:

```bash
philwo@philwo-macbookpro ~/src/continuous-integration/buildkite (master *) macs which md5
[1] 22:08:13 [SUCCESS] macpro1
/sbin/md5
[2] 22:08:14 [SUCCESS] macpro5
/sbin/md5
[3] 22:08:15 [SUCCESS] macpro4
/sbin/md5
[4] 22:08:15 [SUCCESS] macpro3
/sbin/md5
[5] 22:08:17 [SUCCESS] macpro2
/sbin/md5
[6] 22:08:17 [SUCCESS] macpro6
/sbin/md5
[7] 22:08:17 [SUCCESS] macpro7
/sbin/md5
[8] 22:08:18 [SUCCESS] macpro8
/sbin/md5
```

The problem is our friend, --experimental_strict_action_env, which sets a way too limited default PATH: /bin:/usr/bin. Thus /sbin/md5 won't be on the PATH and thus doesn't work.

See https://github.com/bazelbuild/bazel/blob/2dca40b3b4d90899ff0ad8c7451cea835c83f783/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelConfiguration.java#L176

Suggested "fix": `--action_env=PATH=/usr/bin:/bin:/usr/sbin:/sbin`

WDYT?

**Comment by ulfjack** [comment]
--action_env might not work due to not actions picking it up.
Alternatively, we could also consider putting /sbin on the PATH by default
in Bazel, either only for MacOS or for both Linux and MacOS.

**Comment by buchgr** [comment]
I have disabled strict action env
