### ISSUE TITLE
CI for https://github.com/bazelbuild/examples/

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#225]
Ideally, BuildKite should test this repository: https://github.com/bazelbuild/examples/

There are multiple WORKSPACE files, so I can we have to run `bazel test //...` in multiple directories.

**Comment by buchgr** [comment]
Thanks for opening the issue. We hit a problem with the multiple `WORKSPACE` files, as we are reluctant to add configuration that allows a build to `cd` into a directory.

Could we possibly refactor the code so that `bazel test ...` just works?

**Comment by laurentlb** [comment]
The idea was to have multiple independent tutorials. And each tutorial needs its own WORKSPACE file. For example: https://github.com/bazelbuild/examples/tree/master/tutorial

But I see that WORKSPACE files don't have much content, so refactoring should be possible.

**Comment by alexeagle** [comment]
We need this feature for rules_typescript and rules_nodejs.

We have lots of path handling bugs where we don't account for external workspaces, so we must always test with nested workspaces. I would expect other rules should do this too.

Right now we use CircleCI to do this, but we are paying a lot of extra maintenance cost to keep a separate CI around, and last week we broke it with a google3 change since those only run against buildkite.
We need a way to express nested workspaces in the CI. It does'nt have to be `cd` - maybe we could give the name of a `local_repository` to run some other targets in?
