### ISSUE TITLE
BuildKite logs should show the git hash of the commit being tested

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#277]
I am trying to debug a recent TensorFlow failure, and can't identify what commit was tested yesterday to compare against. Having the git commithash printed in the "Fetching sources" step would make this much easier.

**Comment by philwo** [comment]
This was fixed by Buildkite. The tested Git commit hash is visible in several places now:

<img width="460" alt="Screenshot 2019-05-28 at 17 04 11" src="https://user-images.githubusercontent.com/504652/58489018-be41a380-816a-11e9-80c8-90cb5b588afc.png">
<img width="1101" alt="Screenshot 2019-05-28 at 17 04 24" src="https://user-images.githubusercontent.com/504652/58489020-be41a380-816a-11e9-966f-9c394d300219.png">
