### ISSUE TITLE
All Windows agents are disconnected

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#291]
Pipelines are stalled, waiting for Windows agents.
Meanwhile Google Cloud Console shows the agents as running, and I could RDP into one.

**Comment by laszlocsomor** [comment]
Is https://github.com/bazelbuild/continuous-integration/issues/283 related?

**Comment by laszlocsomor** [comment]
@fweikert said the root cause was https://github.com/bazelbuild/continuous-integration/issues/287, which is fixed but not yet deployed to Windows images, so for now the workaround was to re-create the Windows workers.

I see the new agents are connected to BuildKite and pipelines are resuming.

Thanks @fweikert for the quick action!

**Comment by fweikert** [comment]
Root cause: https://github.com/bazelbuild/continuous-integration/issues/287
The startup script crashes upon reboot, hence the agent never comes up.

The fix still needs to be deployed to the windows VM images. For now, I simply deleted the old instances and created new ones as a workaround. Windows agents are now back online.

**Comment by laszlocsomor** [comment]
This is happening again. My presubmit (https://buildkite.com/bazel/google-bazel-presubmit/builds/4655) is timing out because there are no Windows workers.
/cc @buchgr

**Comment by fweikert** [comment]
Fix should have been deployed by now.
