### ISSUE TITLE
Ubuntu 18.04 JDK9 tests failing due to low memory

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#340]
Logs: https://buildkite.com/bazel/bazel-bazel/builds/4841#740e40dc-717d-44c0-af55-8feafeeb7e80
Work was buildkite-worker-ubuntu1804-java9-r5pz-1

Looms like the following:

- bazel-rules-tests
- filegroup-rules-tests
- AndroidLibraryTest
- ObjcRulesTests
- PlatformRulesTests
- android_instrumentation_test_integration_test
- bazel_bootstrap_distfile_test
- bazel_determinism_test
- build_files_test
- maven_test
- discard_analysis_cache_test

I have restarted the tests to see if they pass on another worker.

**Comment by philwo** [comment]
I think it's likely that we ran into a process limit on the system and not an actual memory issue, because the machines have ~120 GB of RAM and I found this line in "dmesg" which happened roughly during the failed test run:

2018-10-03T14:42:55,377345+0000 cgroup: fork rejected by pids controller in /system.slice/buildkite-agent.service

According to a SuSE doc about this error, we have to verify and maybe override the limit set in the systemd configuration for that service: https://www.suse.com/support/kb/doc/?id=7022001

Systemd tells us that the limit is already quite high, but maybe still not enough (because Bazel looooves threads):

```
$ systemctl status buildkite-agent.service
[...]
    Tasks: 44 (limit: 4915)
```

We could try bumping it up even more.

**Comment by katre** [comment]
The tests passed on a re-run.

**Comment by katre** [comment]
Haven't seen this recently. Re-open if needed.
