### ISSUE TITLE
Github PR UI says status for required checks isn't reported

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/continuous-integration#385]
See for instance [rules_python #135](https://github.com/bazelbuild/rules_python/pull/135) (though that might be merged by the time you read this). The checks `cla/google` and `buildkite/rules-python-python` have completed. All other checks have not:

- `bazel build (Ubuntu 14.04)`
- `bazel build (Ubuntu 16.04)`
- `bazel build (macOS)`
- `bazel test (Ubuntu 14.04)`
- `bazel test (Ubuntu 16.04)`
- `bazel test (macOS)`

Is this a problem with rules_python's configuration or with buildkite?

**Comment by brandjon** [comment]
Ping @fwe -- the PRs in rules_python are still exhibiting this. Any ideas?

**Comment by brandjon** [comment]
Ping @jin, @meteorcloudy, any idea what needs changing?

**Comment by jin** [comment]
On first glance, this looks like Buildkite webhook configuration is misconfigured to fire its events back to GItHub.

**Comment by brandjon** [comment]
For whatever reason it looks like this is green now, albeit with a different set of builds/checks running, which actually looks more reasonable than whatever it was doing before.

Perhaps the wrong build and test commands were running before, and it got cleaned up as part of this pipeline slug thing I see in the commit history?

**Comment by philwo** [comment]
This happens when one of these checkboxes is flipped in the Buildkite Pipeline Settings *and* the results of the Buildkite jobs have been added as required checks in the branch protection of a GitHub repo:

<img width="817" alt="Screenshot 2019-05-28 at 16 51 41" src="https://user-images.githubusercontent.com/504652/58488054-ffd14f00-8168-11e9-85f4-f4fc29a75890.png">

<img width="690" alt="Screenshot 2019-05-28 at 16 52 59" src="https://user-images.githubusercontent.com/504652/58488108-15df0f80-8169-11e9-94e0-9661586dac4c.png">

The reason is that the checkboxes on the Buildkite side change the name of the checks that get reported to GitHub and GitHub will then wait forever for the older checks to appear and turn green.
