### ISSUE TITLE
Allow users to request a specific Buildifier version

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#530]
The first (unmerged) version of Buildifier support allowed users to specify a version number in the presubmit configuration.

Users have asked us for this functionality, so we should bring it back. However, it might be better to simply run the buildifier target and leave the versioning to the WORKSPACE file.

**Comment by fweikert** [comment]
Additional AI: Add the version number of the Buildifier binary to the label of the Buildifier step, similar to what we already do for "Bazel Build" and "Bazel Test".

**Comment by fweikert** [comment]
I though about using the Buildifier reference from the WORKSPACE file, but I don't like this idea:
1. Users have to specify commit hashes in the WORKSPACE file, and our wrapper would print "unreleased Buildifier" as a result. This approach is far less user friendly than letting them specify a version string such as "0.20.0", which could then be printed by our wrapper.
2. Using Buildifier from the WORKSPACE file means that we have to set up and invoke bazel. I'd rather prefer to call the GitHub API to get a list of releases and the relevant Buildifier binary.

**Comment by fweikert** [comment]
My proposal:
- Get rid of Docker
- Merge the buildifier.py wrapper into bazelci.py and call the code via a top-level command (e.g. "python bazelci.py buildifier")

**Comment by philwo** [comment]
The issues you identified with the WORKSPACE file approach are quite problematic, indeed! :| Not being able to show the correct version number of the tool sounds like pretty bad UX.

Regarding "we would always have to invoke Bazel": Not great, but maybe not a big problem (if we get user happyness / features in return).

I think we could solve the version number problem by fetching the list of releases from GitHub and creating a map of version numbers to their Git commit hashes and then showing them preferably (and falling back to the commit in case someone really is using Buildifier from an unreleased commit).

Regarding the proposal, I'm not a fan of:
- Running tools on our Docker hosts not inside Docker containers. This is for security, reliability and maintenance reasons. The leaner and smaller our Docker image is, the less often we have to rebuild and redeploy it. :)
- Adding more features to the bazelci.py script. It is already way too huge and complex and hard to maintain.

Why can't we just extend the current mechanism that uses Docker?

In general (doesn't have to be right now, but we also shouldn't go into a direction that makes this hard), I would like the Buildifier integration to go more towards being a reusable [Buildkite plug-in](https://buildkite.com/docs/pipelines/plugins) rather than a feature coded specifically for our CI. Think about the impact if you make it possible for Bazel users that aren't on our CI (but also use Buildkite), like bigger companies, to easily add Buildifier to their pipelines, too. That would be quite a nice extension to Bazel's ecosystem. :)

**Comment by fweikert** [comment]
All commits have been deployed.
