### ISSUE TITLE
Allow users to blacklist/whitelist specific Buildifier warnings

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#531]
Some users might want to run a non-standard subset of Buildifier warnings. Ideally this subset would be configurable via the presubmit settings.

**Comment by meteorcloudy** [comment]
Should buildifier fail the job? 
eg. https://buildkite.com/bazel/bazel-toolchains/builds/1350#28d4d9a9-0d9c-474f-87c5-9cf309bbe0cf

The updating last green commit step got blocked because buildifier step failed.

**Comment by fweikert** [comment]
It's WAI that Buildifier failed the job (since otherwise no one would look at the results). However, we should find a way to unblock the "update last green" step.

**Comment by philwo** [comment]
I think it's WAI that the Buildifier step fails the job, *but* it is super problematic that we update Buildifier globally on CI and don't version it with each individual repository.

This way, pipelines will suddenly break (because new Buildifier versions add newer / stricter checks) at no the fault of the repository itself.

Unfortunately I didn't take this into account when I initially reviewed Florian's code and told him that we don't need to be able to do that. (He already had support for specifying the version of Buildifier to be used in the CI config in the first iteration :()

@fweikert Can we somehow bring back your feature to use a specific Buildifier version per config, or alternatively expedite the "Use Buildifier specified in the WORKSPACE file" feature?

**Comment by fweikert** [comment]
@philwo Already working on it: https://github.com/bazelbuild/continuous-integration/issues/530

**Comment by fweikert** [comment]
Also filed https://github.com/bazelbuild/continuous-integration/issues/543

**Comment by fweikert** [comment]
Fix has been deployed.

**Comment by fweikert** [comment]
Tested:

---
buildifier:
  version: latest
  warnings: rule-impl-return

-> https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/1985
