### ISSUE TITLE
bazelisk-plus-incompatible-flags should show failures

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/continuous-integration#555]
The pipeline shows everything as green, e.g. https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/37

However, many of the projects actually need to be migrated. It's hard to find which projects should be fixed. It would be nice to show them as red.

For example, if I care about 4 projects, and each of them is tested on 3 platforms, I have to open 12 logs just to know if I have anything to do.

**Comment by laurentlb** [comment]
cc @meteorcloudy

**Comment by meteorcloudy** [comment]
@laurentlb Instead of failing the job, how about we add a warning sections for the projects that need migration.
Like this:
https://buildkite.com/bazel/pcloudy-test/builds/19

I'm unwilling to add more complicate logic to bazelci.py just for this pipeline. And keeping the pipeline green make us less nervous

**Comment by laurentlb** [comment]
Looks good
