### ISSUE TITLE
Request to add new project codelabs

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/continuous-integration#676]
- I want to test the following project on Bazel CI: [https://github.com/bazelbuild/codelabs]
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
Done!

Your project currently fails on Windows, because there are no tests: https://buildkite.com/bazel/bazel-codelabs/builds/1#d832f7f5-8073-4a8d-ac62-ffe8577267c5

Could you have a look at that?

Green Team: Feel free to remove the disable_reason once the project has been green in the disabled downstream pipeline.
