### ISSUE TITLE
Request to add new project bazel-tools

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/continuous-integration#692]
- I want to test the following project on Bazel CI: https://github.com/atlassian/bazel-tools
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
Hi @ash2k,

I added your project to our CI and configured it to do an hourly build from your master branch. :) You can see the results here: https://buildkite.com/bazel/atlassian-bazel-tools

In order to get read/write access to the pipeline so that you can

- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other colleagues access, too, include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline. :)

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking. This means that the latest stable Bazel version should always work for your project.

If you have any questions, feel free to reach out to me!

**Comment by ash2k** [comment]
@philwo I have sent you an email a few days ago. Thanks for setting it all up!

**Comment by ash2k** [comment]
All done now, cheers!
