### ISSUE TITLE
Android tests need to use version 24

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/continuous-integration#74]
The tutorial build is looking for 21: http://ci.bazel.io/job/Tutorial/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/920/console

This was changed here: https://bazel-review.googlesource.com/c/10932/.

**Comment by kchodorow** [comment]
This needs to be updated: https://github.com/bazelbuild/examples/blob/master/tutorial/ci/setup_android_repositories.sh

**Comment by aj-michael** [comment]
Hmmm, i'm not sure exactly what the best course of action here is. Here are the facts:

1. android_sdk_repository will choose the highest installed API level to use by default if the api_level attribute is not set.
2. android_sdk_repository will fail if the attribute is not set and no API levels are installed
3. android_integration_test currently will fail if you do not have API level 24 installed: https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/android/android_integration_test.sh#L389
4. I don't know what API level the example app code was written against, but presumably there exists an N such that the build will fail with api_level < N.
5. android_integration_test requires that the "Android Support Repository" be installed by the SDK: https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/android/android_integration_test.sh#L199

Regarding #3, I can change that test to look for an installed API level, and use that instead of requiring API level 24. Regarding #4, I don't know if there is anything we can do. Regarding #5, I don't know of any other way to test our handling of the Android support repository.


@ahumesky , any idea on how we can make our CI more robust at handling Android SDKs?

**Comment by ahumesky** [comment]
For 4, apis should be backwards compatible, so the example code itself should be fine.
For 5, we can modify the mac-android.sh script to also install the android support repository, you just have to find the right sdkmanager command line (same for linux-android.sh)

**Comment by kchodorow** [comment]
Note: this is also causing the main repo's (bazelbuild/bazel) build to fail: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/751/console

**Comment by aj-michael** [comment]
Fix in https://bazel-review.googlesource.com/11070, verifying it now.

**Comment by philwo** [comment]
I'll have a look. I'm curious though, we upgraded the Linux nodes to Android 24 a few weeks ago already - why didn't it cause issues there?

**Comment by kchodorow** [comment]
I did push a CI change yesterday and restarted the master, maybe that's the first time that's happened since your change?
