### ISSUE TITLE
Request to add new project: Google Authenticator Android

### ISSUE THREAD

**Issue by MrPickles** [bazelbuild/continuous-integration#743]
- I want to test the following project on Bazel CI:
  - https://github.com/google/google-authenticator-android
  - https://github.com/mrpickles/google-authenticator-android
- I confirm that the project has a `.bazelci/presubmit.yml` file.

I also want to include my personal fork (see second sub-bullet) to minimize disturbances to the main repo while setting this up. The project name for my fork doesn't really matter.

**Comment by philwo** [comment]
Hi @MrPickles,

I added your project to our CI and configured it to do a daily build from your master branch. :) You can see the results here:
- https://buildkite.com/bazel/google-google-authenticator-android/builds/1
- https://buildkite.com/bazel/mrpickles-google-authenticator-android/builds/1

In order to get read/write access to the pipeline so that you can
- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] get build badges that you can show on GitHub,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other people access, too, please include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline.

When you received the invite:
- Setup the GitHub webhook via these links:
  - https://buildkite.com/bazel/google-google-authenticator-android/settings/setup/github
  - https://buildkite.com/bazel/mrpickles-google-authenticator-android/settings/setup/github
- Connect your Buildkite account to your GitHub account via this link: https://buildkite.com/user/connected-apps. This ensures that Buildkite can push commit status updates to your project.

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking.

If your pipeline is broken on our CI for a longer time and there's no response to issues that we file on your GitHub project, we'll have to remove your project again.

If you have any questions, feel free to reach out to me!

**Comment by philwo** [comment]
Hi @MrPickles,

your project has never been green on Bazel's CI, because we didn't install the version of Android build-tools that your project requires (28.0.3). I just noticed this while checking out which projects are failing.

While I can just install the missing version, I wonder what the motivation was to add the project to our CI, if apparently no one noticed that it was broken all the time 😅

Do you still want this project on Bazel's CI? If yes, let's work together on making it green and keeping it that way. If not, let me know and I can also remove it again.

Thanks!

**Comment by MrPickles** [comment]
Hi Philipp, I actually left Google a week before you set up the pipeline. 🙃

I'd imagine that it would still be nice to keep the CI and make it green though! Since the repo is open source, I wouldn't mind doing some short-term maintenance and handoff, but I wont be able to make any longer term promises.

cc @ThomasHabets @dongjing-github

**Comment by jin** [comment]
This would be really useful for test coverage of Android apps 👍

**Comment by philwo** [comment]
Thanks for the feedback @MrPickles and @jin 😄

I'll roll out new images with the build-tools 28.0.3 today, so hopefully the project will just turn green then. If not and I need your help, I'll ping here. :)

**Comment by jin** [comment]
I don't think any of the Android projects on CI now pin their build tools versions. To simplify future maintenance, @MrPickles can you remove the build tools versions pin in the WORKSPACE?

**Comment by MrPickles** [comment]
@jin I removed it for my personal fork. If I see that both repos are green, I'll make a pull request into the upstream repo.

**Comment by philwo** [comment]
@MrPickles I triggered a CI run for your fork: https://buildkite.com/bazel/mrpickles-google-authenticator-android/builds/73

I think we'll have to upgrade some dependencies in the WORKSPACE file so that they work with the latest Bazel version.

**Comment by MrPickles** [comment]
Sure, I can take a look at it this weekend. Might not have that much bandwidth to work on it during the weekdays, since, you know... I don't work at Google anymore 😛

**Comment by fweikert** [comment]
I deactivated daily builds for this pipeline since they've been failing forever. Are there any plans to fix the problems?

**Comment by fweikert** [comment]
Closing this issue since the onboarding request has been fulfilled.
