### ISSUE TITLE
Request to add new project rules_proto_grpc

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/continuous-integration#766]
- I want to test the following project on Bazel CI: https://github.com/rules-proto-grpc/rules_proto_grpc
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
Hi @aaliddell,

I added your project to our CI and configured it to do a daily build from your master branch. :) You can see the results here: https://buildkite.com/bazel/rules-proto-grpc-rules-proto-grpc/builds/1

In order to get read/write access to the pipeline so that you can
- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] get build badges that you can show on GitHub,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other people access, too, please include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline.

When you received the invite:
- Setup the GitHub webhook via this link: https://buildkite.com/bazel/rules-proto-grpc-rules-proto-grpc/settings/setup/github
- Connect your Buildkite account to your GitHub account via this link: https://buildkite.com/user/connected-apps. This ensures that Buildkite can push commit status updates to your project.

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking.

If your pipeline is broken on our CI for a longer time and there's no response to issues that we file on your GitHub project, we'll have to remove your project again.

If you have any questions, feel free to reach out to me!

**Comment by aaliddell** [comment]
Thanks!

Webhook has been configured and is tested working. Status reports are not getting back to GitHub though and Buildkite shows this error:

> Buildkite has temporarily turned off commit status updates for this build pipeline

I have a feeling this is due to reports sent prior to linking my account to the project which would have failed, so we'll see if they reactivate now these are linked (whenever 'temporarily' expires). I have checked the org access is enabled for Buildkite to this repo also.

I'll keep an eye on that message and close this once they're getting through :+1:

**Comment by philwo** [comment]
@aaliddell I've manually enabled them again (by checking the "Update commit statuses" option) - let's see if it works!

If you...
- linked your Buildkite account with your GitHub account,
- granted it access to the rules-proto-grpc organization and
- have write access to the rules-proto-grpc/rules-proto-grpc repository,

it should work. :) Let me know.

**Comment by aaliddell** [comment]
Ah, I missed that option. It's now working, thanks :tada:
