### ISSUE TITLE
Request to add new project Meteo API

### ISSUE THREAD

**Issue by piotr-maks** [bazelbuild/continuous-integration#778]
- I want to test the following project on Bazel CI: https://github.com/piotr-maks/meteo-api
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
Hi @piotr-maks,

I added your project to our CI and configured it to do a daily build from your master branch. :) You can see the results here: https://buildkite.com/bazel/piotr-maks-meteo-api/builds/1

In order to get read/write access to the pipeline so that you can
- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other people access, too, please include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline.

When you received the invite:
- Setup the GitHub webhook via this link: https://buildkite.com/bazel/piotr-maks-meteo-api/settings/setup/github
- Connect your Buildkite account to your GitHub account via this link: https://buildkite.com/user/connected-apps. This ensures that Buildkite can push commit status updates to your project.

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking.

If your pipeline is broken on our CI for a longer time and there's no response to issues that we file on your GitHub project, we'll have to remove your project again.

If you have any questions, feel free to reach out to me!

**Comment by piotr-maks** [comment]
Hi @philwo,

I wonder if it is possible to target C++17 for Windows pipeline? Right now I can see warnings which makes me worried:
`(08:16:23) INFO: From Compiling test/hello-test.cc:
cl : Command line warning D9002 : ignoring unknown option '/std:c++17'`
https://buildkite.com/bazel/piotr-maks-meteo-api/builds/3#1064f2f8-ae52-4c48-8023-f26c579eb3a6

**Comment by philwo** [comment]
I'm removing this project from our CI, because the repository has apparently been deleted.
