### ISSUE TITLE
Show which target failed on ci.bazel.io

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/continuous-integration#81]
When a build fails on ci.bazel.io, we have no idea why it failed, which target failed (e.g. [this build](http://ci.bazel.io/view/Dashboard/job/gerrit/lastCompletedBuild/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/testReport/com.google.gerrit.acceptance.pgm/ReindexIT/reindexFromScratch/). That makes reproducing the build harder and slower. Can we improve this?

**Comment by damienmg** [comment]
(Please /cc instead of assigning if no immediate work is needed)

The jenkins dashboard is terrible, the new pipeline I am preparing is a bit better and I have an idea to make it even better, not sure the work is worth it.

FYI the command to run is available on the [overly verbose log](http://ci.bazel.io/view/Dashboard/job/gerrit/435/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/console), and you might also want to see the [bazel.bazelrc](http://ci.bazel.io/view/Dashboard/job/gerrit/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/ws/bazel.bazelrc/*view*/) file

**Comment by damienmg** [comment]
Closing as this is being superseded by the work on the new UI
