### ISSUE TITLE
Request to add new project google-cloud-cpp-spanner

### ISSUE THREAD

**Issue by tmatsuo** [bazelbuild/continuous-integration#811]
- I want to test the following project on Bazel CI: https://github.com/googleapis/google-cloud-cpp-spanner
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by tmatsuo** [comment]
Ping...

**Comment by philwo** [comment]
Hi @tmatsuo,

I added your project to our CI and configured it to do a daily build from your master branch. :) You can see the results here: https://buildkite.com/bazel/github-dot-com-googleapis-google-cloud-cpp-spanner/builds/1

In order to get read/write access to the pipeline so that you can
- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] get build badges that you can show on GitHub,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other people access, too, please include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline.

When you received the invite:
- Setup the GitHub webhook via this link: https://buildkite.com/bazel/github-dot-com-googleapis-google-cloud-cpp-spanner/settings/setup/github
- Connect your Buildkite account to your GitHub account via this link: https://buildkite.com/user/connected-apps. This ensures that Buildkite can push commit status updates to your project.

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking.

If your pipeline is broken on our CI for a longer time and there's no response to issues that we file on your GitHub project, we'll have to remove your project again.

If you have any questions, feel free to reach out to me!

**Comment by tmatsuo** [comment]
Thanks! I'm thinking to add the build badge to the README. I have a question. What version of Bazel is used for the daily build? Is it always using the head, or the latest release, or something else?

It seems like the last daily build is using 0.29.1, but it seems like there's 1.0.0 released recently. Will the next build use 1.0.0?

**Comment by tmatsuo** [comment]
I noticed that the builds started using 1.0.0 and our build broke :)

Anyways, I'd close this issue. It's serving well so that it caught the breakage ;)

**Comment by philwo** [comment]
Hi @tmatsuo - yes, Bazel CI will use the latest stable release by default. Upgrades happen immediately after the release.

We do run downstream tests of Bazel HEAD and release candidates against well maintained projects (i.e. those that keep their CI builds green and apply pending migrations for incompatible flags) and will use this information to prevent accidental breakages, so hopefully in the future a new Bazel release will not break your project. :)

If you have any questions or comment, please always feel free to reach out to me!
