### ISSUE TITLE
Request to add new project Brightspace/rules_csharp

### ISSUE THREAD

**Issue by j3parker** [bazelbuild/continuous-integration#832]
I would like to test the following project on Bazel CI: https://github.com/brightspace/rules_csharp

I confirm that the project has a [`.bazelci/presubmit.yml`](https://github.com/brightspace/rules_csharp/blob/master/.bazelci/presubmit.yml) file.

I added multiple platforms but kept it pretty basic (and skipped the RBE platform because I think we might have problems with it to start). If you want me to slim it down some more to start that's fine!

**Comment by philwo** [comment]
Hi @j3parker,

I added your project to our CI and configured it to do a daily build from your master branch. :) You can see the results here: https://buildkite.com/bazel/github-dot-com-brightspace-rules-csharp/builds/1

In order to get read/write access to the pipeline so that you can
- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] get build badges that you can show on GitHub,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other people access, too, please include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline.

When you received the invite:
- Setup the GitHub webhook via this link: https://buildkite.com/bazel/github-dot-com-brightspace-rules-csharp/settings/setup/github
- Connect your Buildkite account to your GitHub account via this link: https://buildkite.com/user/connected-apps. This ensures that Buildkite can push commit status updates to your project.

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking.

If your pipeline is broken on our CI for a longer time and there's no response to issues that we file on your GitHub project, we'll have to remove your project again.

If you have any questions, feel free to reach out to me!

**Comment by j3parker** [comment]
🎉 Thank you! This is so cool! I sent the email.

**Comment by j3parker** [comment]
Okay - I followed the steps, added the build badge to the repo and switched our branch protection rules over to this CI. Everything looks good on our end! Feel free to close this issue if there is nothing left on yours.

**Comment by philwo** [comment]
Nice, glad to hear that! I'm closing this issue then :)
