### ISSUE TITLE
Request to add new project rules_m4

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/continuous-integration#841]
- I want to test the following project on Bazel CI: https://github.com/jmillikin/rules_m4
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by philwo** [comment]
Hi @jmillikin,

I added your project to our CI and configured it to do a daily build from your master branch. :) You can see the results here: https://buildkite.com/bazel/github-dot-com-jmillikin-rules-m4/builds/1

In order to get read/write access to the pipeline so that you can
- [x] setup a webhook for GitHub triggering and pull request testing,
- [x] test individual commits, tags and other branches than master,
- [x] retry failed builds,
- [x] get build badges that you can show on GitHub,
- [x] and more,

please send me an e-mail (my address is in my GitHub profile) and if you'd like to give other people access, too, please include their addresses. I'll then send you Buildkite invites for a team that has read/write access to your pipeline.

When you received the invite:
- Setup the GitHub webhook via this link: https://buildkite.com/bazel/github-dot-com-jmillikin-rules-m4/settings/setup/github
- Connect your Buildkite account to your GitHub account via this link: https://buildkite.com/user/connected-apps. This ensures that Buildkite can push commit status updates to your project.

Now that your project is on our CI, we will also test new Bazel releases against your project and will ensure we don't accidentally break you. We're still working out a detailed support policy, but the deal is basically: As long as you keep your CI pipeline green and do timely migrations of your code as outlined in the [incompatible changes process](https://docs.bazel.build/versions/master/backward-compatibility.html), we'll block releases and incompatible flag flips on your build not breaking.

If your pipeline is broken on our CI for a longer time and there's no response to issues that we file on your GitHub project, we'll have to remove your project again.

If you have any questions, feel free to reach out to me!

**Comment by jmillikin** [comment]
This is set up and working; build's green on master. Thanks again for your help!

**Comment by philwo** [comment]
Hi @jmillikin,

I noticed that all of your projects on Bazel CI are red, most of them for a while:

- https://buildkite.com/bazel/github-dot-com-jmillikin-rules-bison
- https://buildkite.com/bazel/github-dot-com-jmillikin-rules-flex
- https://buildkite.com/bazel/github-dot-com-jmillikin-rules-m4
- https://buildkite.com/bazel/github-dot-com-jmillikin-rules-ragel

Do you want to fix them, or are they unmaintained? I'm looking to reduce the complexity / scope of our Bazel CI setup a bit to only keep projects that stay green, so that we can get a good test signal out of them. If they're not regularly maintained to keep up with Bazel's changes, maybe testing these projects using GitHub Actions instead is an option?

In case that's interesting, we've recently added support for Bazelisk that should make it really easy: https://github.com/marketplace/actions/setup-bazelisk

Let me know what you think!

**Comment by jmillikin** [comment]
Hi Philipp,

The pandemic (+ related events) have limited the time I have to work on
personal projects, and they started to hit an apparent issue in Bazel CI
where the build is marked as "failed" if the same commit is built too many
times.

Because of this I wasn't paying attention to the red builds, and didn't
notice that the Buildifier lints had at some point started failing. I will
look at your PRs soon (hopefully this weekend). If the original "red from
too many builds" issue recurs (last time it IIRC took many months), I'll
file a ticket rather than ignore it.

**Comment by philwo** [comment]
Hi John,

No worries and thanks for getting back to me here. Hopefully just bumping the Buildifier version will already fix them. 😊  Let me know if I can help in any way and take your time.

Cheers,
Philipp

**Comment by jmillikin** [comment]
OK, those four repos now have green Bazel CI builds at trunk.
