### ISSUE TITLE
Request to add new project rules_openapi/rules_avro

### ISSUE THREAD

**Issue by chenrui333** [bazelbuild/continuous-integration#874]
- I want to test the following projects on Bazel CI: 
    - https://github.com/meetup/rules_openapi
    - https://github.com/chenrui333/rules_avro/
- I confirm that the project has a `.bazelci/presubmit.yml` file.

Thanks!

**Comment by chenrui333** [comment]
Relates to https://github.com/meetup/rules_openapi/pull/25

**Comment by chenrui333** [comment]
cc @philwo

**Comment by philwo** [comment]
Hi @chenrui333,

I'm so sorry that it took so long :( I created the pipelines on Bazel's CI now.

Here are the first runs:
- https://buildkite.com/bazel/meetup-rules-openapi/builds/1
- https://buildkite.com/bazel/chenrui333-rules-avro/builds/1

I sent you a Buildkite invite to your e-mail - once you accept it, I can add you to the teams with admin access to the two projects. Then you can configure GitHub webhooks for your repositories and get presubmit testing for pull requests and get commit statuses pushed to GitHub.

If you haven't done so, please connect your GitHub user to Buildkite via https://buildkite.com/user/connected-apps, so that Buildkite has the permission to push commit status information to repositories you own.

If you have any questions, let me know!

**Comment by fweikert** [comment]
Closing this issue for now. Please let me know if you still want to test on Bazel CI.
