### ISSUE TITLE
Issue seems to have been filed, but info doesn't show any breaking information

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#893]
We had https://github.com/bazelbuild/rules_apple/issues/672 filed, but looking at the referenced log, it shows the whole step as green, does list the flag under _Migration is needed for the following flags:_, but in the output, there doesn't appear to be anything to say what actually failed to let one see what the problem was; attached is the screen show of the UI I'm seeing.

![Screen Shot 2019-12-19 at 10 05 38 AM](https://user-images.githubusercontent.com/5279928/71184065-24952d00-2247-11ea-9c50-032e451aa8af.png)

**Comment by alexeagle** [comment]
Same for rules_nodejs, I suspect these bot-filed issues were for 1.2 and no longer apply?

**Comment by jayconrod** [comment]
Same for rules_go. I found the test results hard to read. Everything's green, but it you click through the disclosure triangles for some of the steps with flags, there are errors. Only some of the steps though, and only on some platforms. It's hard to find what went wrong.

The actual issues aren't very helpful either. They should link to the tracking issue for each incompatible flag with migration instructions. If there's any person managing these flags they should be cc'd. Not obvious who I would ask for help with some of the more complicated flags. The issue markdown isn't correct (link addresses are HTML tags instead of URLs).

**Comment by fweikert** [comment]
There were several bugs related to the title and content of issues, all of which I have fixed. You should see new issues soon.

For example, the version number 1.2.1 was wrong (since we only flip flags in major releases).
@thomasvl Unfortunately Buildkite truncates large logs, so you have to click on "Download" in the top right corner to see the error.

**Comment by fweikert** [comment]
There will also be fewer issues since we released 2.0 in the meantime.
