### ISSUE TITLE
Cannot tell why build is UNSTABLE

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#91]
I set https://bazel-review.googlesource.com/c/13391 as "Pre-Submit +1", and the test pipeline ran. When it finished, the pipeline was marked as finishing UNSTABLE and the change was marked as "Verified: -1".

The link is: http://ci.bazel.io/blue/organizations/jenkins/CR%2Fbazel-tests/detail/bazel-tests/141/pipeline/

1. The link goes to the entire pipeline, which isn't useful. It took me a while to realize I need to click the "Tests" at the top right to see the actual results.
2. The "Tests" tab says that all tests pass. So why is the change marked UNSTABLE? I can't determine that anywhere.

**Comment by damienmg** [comment]
Yes this is due to a bug in Jenkins that a step cannot be marked as
unstable (https://issues.jenkins-ci.org/browse/JENKINS-26522 is supposed to
address that), just the whole pipeline. And the fact this is combined to
the fact that timeout does not generate XML files. Unfortunately this is
not easy to fix right now but I might have an idea for it.

Low priority anyway, you can browse the various configuration or the full
log to find out which test timed-out.

**Comment by damienmg** [comment]
FTR The bazel bug is https://github.com/bazelbuild/bazel/issues/1027

**Comment by katre** [comment]
@damienmg, even with you telling me that the issue is a timeout, I can't tell where in that page I could find out what timed out, much less why. This is impenetrable.

**Comment by damienmg** [comment]
So the test output is being fixed on both the sandbox by @philwo and the default XML generator (https://bazel-review.googlesource.com/c/13471).

I have went to see the failure and cannot spot the issue either, I need to add more debugging too.

**Comment by damienmg** [comment]
http://ci.bazel.io/job/CR/job/bazel-tests/141/execution/node/431/log/ is showing actual test failures, but not reported in the test.xml files...

**Comment by damienmg** [comment]
Ok the workspace already got overwritten, cannot get more info from it. It's weird though it got overwritten by another conf, let me try to spot this other problem
