### ISSUE TITLE
CI build doesn't provide enough information to debug issue

### ISSUE THREAD

**Issue by achew22** [bazelbuild/continuous-integration#978]
Recently I've been having issues with [builds on Windows](https://buildkite.com/bazel/bazel-watcher/builds/1137).

If you go over to the "Artifacts" tab, you'll see something like `e2e/output_runner/attempt_x.log` which right now points to this: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/5ef93a2d-8865-471c-80b1-b0a3ee8c46dc/e2e%5Coutput_runner%5Cgo_default_test%5Cattempt_1.log

```
    TestNotifyWhenInvalidConfig: output_runner_test.go:131: Unable to build target. Error code: 36
        Stdout:
        
        Stderr:
        Loading: 
        Loading: 0 packages loaded
        DEBUG: C:/b/hfjzu6i5/bazel_testing/bazel_go_test/main/defs.bzl:3:3: not it
        Analyzing: target //:test (1 packages loaded, 0 targets configured)
        INFO: Analyzed target //:test (1 packages loaded, 2 targets configured).
        INFO: Found 1 target...
        ERROR: Source forest creation failed: C:\b\idfxtqud\execroot\__main__\external
        INFO: Elapsed time: 0.120s
        INFO: 0 processes.
        FAILED: Build did NOT complete successfully
        FAILED: Build did NOT complete successfully
--- FAIL: TestNotifyWhenInvalidConfig (0.17s)
```

The error code of 36 refers to `36 - Local Environmental Issue, suspected permanent.`. I really wish Bazel printed out more in this case, but I suspect it is an issue with the CI system or possibly a bug in Bazel since the error comes from [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java;l=475?q=%22Source%20forest%20creation%22&ss=bazel) and doesn't seem to be associated with any user-provided code.

Is there a way to get the CI system to output more information about this error?

**Comment by philwo** [comment]
@achew22 The CI system already prints / uploads all information that Bazel provides. The build log contains the full stdout / stderr and the artifacts are the test logs uploaded as they're generated by Bazel without any processing.

Unfortunately the CI system does not know any more about this error than it prints. :(

The root cause seems to be this line:
```
ERROR: Source forest creation failed: C:\b\idfxtqud\execroot\__main__\external
```

I would modify whatever code prints this to include more debugging output and try again. One classic issue is that code assumes that it can just rename / remove files that might still be open by other processes. Which works fine on Linux and macOS, but fails on Windows.

**Comment by achew22** [comment]
@philwo, that line comes from [Bazel itself](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildtool/ExecutionTool.java;l=475?q=%22Source%20forest%20creation%22&ss=bazel). Are you saying this is a bug in Bazel?

**Comment by philwo** [comment]
@achew22 It could be a bug in Bazel or it could be a bug in the tool driving Bazel here. For example, a classic problem is when one spawns a process, that spawns subprocesses, everything opens files all over the place, then you kill the main process and immediately assume that it's now safe to touch or delete the files that the processes generated. This fails because a) we have to wait for the process to exit after killing it and b) the subprocesses are not automatically killed and might still have open file handles.

I can't immediately spot an issue like that in your test code, but maybe it gives you an idea where to look?

**Comment by achew22** [comment]
Unfortunately I don't have a windows box on which to rapidly iterate and appears to be a flake so this is more than I can handle. I'll close the issue and reopen if it becomes a regular occurrence.
